#!/usr/bin/env python3

"""
SSH Agent配置生成器
作者: saul
版本: 1.0
描述: 生成独立的SSH Agent配置文件，用于.zshrc引用
"""

import os
import sys
from pathlib import Path

# 添加scripts目录到Python路径
script_dir = Path(__file__).parent
sys.path.insert(0, str(script_dir.parent))

try:
    from common import *
except ImportError:
    print("错误：无法导入common模块")
    sys.exit(1)

def generate_ssh_agent_config():
    """
    生成SSH Agent配置文件

    Returns:
        bool: 生成是否成功
    """
    config_path = Path.home() / ".ssh-agent-config.zsh"

    config_content = '''# =============================================================================
# SSH Agent Management - 独立配置文件
# 由 ssh-agent-config-generator.py 自动生成
# =============================================================================

# SSH Agent 延迟初始化函数
_lazy_ssh_agent_init() {
    # 避免重复执行
    [[ -n "$_SSH_AGENT_LAZY_DONE" ]] && return
    export _SSH_AGENT_LAZY_DONE=1

    # 检查现有SSH Agent
    [[ -S "$SSH_AUTH_SOCK" ]] && return

    # 尝试恢复配置
    [[ -f ~/.ssh-agent-ohmyzsh ]] && source ~/.ssh-agent-ohmyzsh 2>/dev/null
    [[ -S "$SSH_AUTH_SOCK" ]] && return

    # 启动新的SSH Agent（完全静默）
    local temp_file=$(mktemp)
    ssh-agent -s > "$temp_file" 2>/dev/null
    source "$temp_file" 2>/dev/null
    cp "$temp_file" ~/.ssh-agent-ohmyzsh 2>/dev/null
    rm -f "$temp_file" 2>/dev/null

    # 加载所有SSH私钥（使用通用模式）
    if [[ -d ~/.ssh && -S "$SSH_AUTH_SOCK" ]]; then
        local keys_loaded=0
        for key_file in ~/.ssh/*; do
            # 检查是否为私钥文件
            if [[ -f "$key_file" && ! "$key_file" =~ \\.(pub|old|bak)$ && ! "$key_file" =~ (known_hosts|authorized_keys|config)$ ]]; then
                if ssh-add "$key_file" 2>/dev/null; then
                    ((keys_loaded++))
                fi
            fi
        done

        # 保存加载统计（用于调试）
        echo "SSH_KEYS_LOADED=$keys_loaded" >> ~/.ssh-agent-ohmyzsh 2>/dev/null
    fi
}

# 只在交互式shell中设置延迟初始化
if [[ -o interactive ]]; then
    # 使用preexec钩子在第一个命令执行前初始化SSH Agent
    autoload -Uz add-zsh-hook
    add-zsh-hook preexec _lazy_ssh_agent_init
fi

# SSH Agent管理别名
alias ast='ssh-add -l 2>/dev/null || echo "SSH Agent not running or no keys loaded"'
alias arl='unset _SSH_AGENT_LAZY_DONE && source ~/.zshrc'
alias adb='echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"; echo "SSH_AGENT_PID: $SSH_AGENT_PID"; echo "Keys loaded:"; ssh-add -l 2>/dev/null || echo "No keys or agent not running"'
'''

    try:
        with open(config_path, 'w') as f:
            f.write(config_content)

        log_success(f"SSH Agent配置文件已生成: {config_path}")
        return True

    except Exception as e:
        log_error(f"生成SSH Agent配置文件失败: {str(e)}")
        return False

def update_zshrc_for_ssh_agent():
    """
    更新.zshrc文件以引用SSH Agent配置

    Returns:
        bool: 更新是否成功
    """
    zshrc_path = Path.home() / ".zshrc"
    config_source_line = "# SSH Agent Management - Auto-generated by ssh-agent-config-generator.py"
    source_line = "[[ -f ~/.ssh-agent-config.zsh ]] && source ~/.ssh-agent-config.zsh"

    if not zshrc_path.exists():
        log_warn(".zshrc文件不存在，创建新文件")
        with open(zshrc_path, 'w') as f:
            f.write(f"{config_source_line}\n{source_line}\n")
        return True

    try:
        with open(zshrc_path, 'r') as f:
            content = f.read()

        # 检查是否已经包含SSH Agent配置引用
        if source_line in content:
            log_info("SSH Agent配置引用已存在于.zshrc中")
            return True

        # 移除旧的SSH Agent配置（如果存在）
        lines = content.split('\n')
        new_lines = []
        skip_ssh_agent_section = False

        for line in lines:
            if "# SSH Agent Management" in line:
                skip_ssh_agent_section = True
                continue
            elif skip_ssh_agent_section and line.strip() == "":
                skip_ssh_agent_section = False
                continue
            elif skip_ssh_agent_section:
                continue
            else:
                new_lines.append(line)

        # 添加新的SSH Agent配置引用
        new_lines.append("")
        new_lines.append(config_source_line)
        new_lines.append(source_line)

        with open(zshrc_path, 'w') as f:
            f.write('\n'.join(new_lines))

        log_success("已更新.zshrc文件以引用SSH Agent配置")
        return True

    except Exception as e:
        log_error(f"更新.zshrc文件失败: {str(e)}")
        return False

def main():
    """主函数"""
    show_header("SSH Agent配置生成器", "1.0", "生成独立的SSH Agent配置文件")

    log_info("开始生成SSH Agent配置...")

    # 生成SSH Agent配置文件
    if not generate_ssh_agent_config():
        log_error("SSH Agent配置文件生成失败")
        return False

    # 更新.zshrc文件
    if not update_zshrc_for_ssh_agent():
        log_error(".zshrc文件更新失败")
        return False

    log_success("SSH Agent配置生成完成！")
    log_info("请运行 'source ~/.zshrc' 或重新启动终端以应用配置")

    return True

if __name__ == "__main__":
    main()
